const courseModel = [
  {
    id: 1,
    name: 'Introduction to React Native',
    likes: 12,
    instructor: 'John Doe',
    description: 'Learn the basics of React Native development and build your first mobile app.',
    enrollmentStatus: 'Open',
    thumbnail: 'https://img.freepik.com/premium-psd/youtube-video-thumbnail-start-trading-today_475351-168.jpg',
    duration: '8 weeks',
    schedule: 'Tuesdays and Thursdays, 6:00 PM - 8:00 PM',
    location: 'Online',
    dueDate:'25th November, 2023',
    progress:'25',
    prerequisites: ['Basic JavaScript knowledge', 'Familiarity with React'],
    syllabus: [
      {
        week: 1,
        topic: 'Introduction to React Native',
        content: 'Overview of React Native, setting up your development environment.',
      },
      {
        week: 2,
        topic: 'Building Your First App',
        content: 'Creating a simple mobile app using React Native components.',
      },
    ],
  },
  {
    id: 2,
    name: 'Advanced JavaScript',
    likes: 4,
    instructor: 'Jane Doe',
    description: 'Deep dive into advanced JavaScript concepts.',
    enrollmentStatus: 'Open',
    thumbnail: 'https://img.freepik.com/premium-psd/youtube-video-thumbnail-start-trading-today_475351-168.jpg',
    duration: '6 weeks',
    schedule: 'Mondays and Wednesdays, 7:00 PM - 9:00 PM',
    location: 'Online',
    dueDate:'25th November, 2023',
    progress:'50',
    prerequisites: ['Intermediate JavaScript knowledge'],
    syllabus: [
      {
        week: 1,
        topic: 'Closures and Scope',
        content: 'Understanding closures and lexical scope.',
      },
      {
        week: 2,
        topic: 'Asynchronous JavaScript',
        content: 'Working with Promises and Async/Await.',
      },
    ],
  },
  {
    id: 3,
    name: 'Advanced JavaScript 2',
    likes : 10,
    instructor: 'Jane Doe',
    description: 'Deep dive into advanced JavaScript concepts.',
    enrollmentStatus: 'Open',
    thumbnail: 'https://img.freepik.com/premium-psd/youtube-video-thumbnail-start-trading-today_475351-168.jpg',
    duration: '6 weeks',
    schedule: 'Mondays and Wednesdays, 7:00 PM - 9:00 PM',
    location: 'Online',
    dueDate:'25th November, 2023',
    progress:'75',
    prerequisites: ['Intermediate JavaScript knowledge'],
    syllabus: [
      {
        week: 1,
        topic: 'Closures and Scope',
        content: 'Understanding closures and lexical scope.',
      },
      {
        week: 2,
        topic: 'Asynchronous JavaScript',
        content: 'Working with Promises and Async/Await.',
      },
    ],
  },
];

export default courseModel;